trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build an image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'sunilc18-docker-hub'
        container: 'sunilc18/currency-exchange-devops'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: $(tag)